export const EVENT_CARD_ADD = 'EVENT_CARD_ADD'
export const EVENT_CARD_DELETE = 'EVENT_CARD_DELETE'
export const EVENT_CARD_UPDATE = 'EVENT_CARD_UPDATE'
export const EVENT_CARDLIST_ADD = 'EVENT_CARDLIST_ADD'
