query BoardWithCardLists($id: ID!){
    board(id: $id){
        id
        title
        color
        cardLists{
            id
            title
            cards{
                id
                title
                order
                owner{
                   id
                    name
                }
                cardList{
                    id
                    board{
                        id
                    }
                }
            }
            board{
                id
                title
                owner{
                    id
                    name
                    email
                }
            }
        }
        owner{
            id
            name
            email
        }
    }

}

